package com.nalpakd.obdscanner.core

/**
 * Offline descriptions for common generic (SAE J2012) trouble codes.
 * Claude provides the in-depth explanation; this is for instant display in the scanner.
 */
object DtcDatabase {

    private val codes: Map<String, String> = mapOf(
        // Fuel & air metering
        "P0010" to "Intake camshaft position actuator circuit (Bank 1)",
        "P0011" to "Intake camshaft timing over-advanced (Bank 1)",
        "P0012" to "Intake camshaft timing over-retarded (Bank 1)",
        "P0013" to "Exhaust camshaft position actuator circuit (Bank 1)",
        "P0014" to "Exhaust camshaft timing over-advanced (Bank 1)",
        "P0015" to "Exhaust camshaft timing over-retarded (Bank 1)",
        "P0016" to "Crankshaft/camshaft position correlation (Bank 1 Sensor A)",
        "P0017" to "Crankshaft/camshaft position correlation (Bank 1 Sensor B)",
        "P0018" to "Crankshaft/camshaft position correlation (Bank 2 Sensor A)",
        "P0019" to "Crankshaft/camshaft position correlation (Bank 2 Sensor B)",
        "P0020" to "Intake camshaft position actuator circuit (Bank 2)",
        "P0021" to "Intake camshaft timing over-advanced (Bank 2)",
        "P0022" to "Intake camshaft timing over-retarded (Bank 2)",
        "P0030" to "O2 sensor heater control circuit (Bank 1 Sensor 1)",
        "P0031" to "O2 sensor heater circuit low (Bank 1 Sensor 1)",
        "P0032" to "O2 sensor heater circuit high (Bank 1 Sensor 1)",
        "P0036" to "O2 sensor heater control circuit (Bank 1 Sensor 2)",
        "P0037" to "O2 sensor heater circuit low (Bank 1 Sensor 2)",
        "P0038" to "O2 sensor heater circuit high (Bank 1 Sensor 2)",
        "P0050" to "O2 sensor heater control circuit (Bank 2 Sensor 1)",
        "P0051" to "O2 sensor heater circuit low (Bank 2 Sensor 1)",
        "P0052" to "O2 sensor heater circuit high (Bank 2 Sensor 1)",
        "P0068" to "MAP/MAF - throttle position correlation",
        "P0087" to "Fuel rail/system pressure too low",
        "P0088" to "Fuel rail/system pressure too high",
        "P0089" to "Fuel pressure regulator performance",
        "P0100" to "Mass air flow (MAF) circuit malfunction",
        "P0101" to "Mass air flow (MAF) circuit range/performance",
        "P0102" to "Mass air flow (MAF) circuit low input",
        "P0103" to "Mass air flow (MAF) circuit high input",
        "P0106" to "Manifold absolute pressure (MAP) range/performance",
        "P0107" to "Manifold absolute pressure (MAP) circuit low",
        "P0108" to "Manifold absolute pressure (MAP) circuit high",
        "P0110" to "Intake air temperature circuit malfunction",
        "P0112" to "Intake air temperature circuit low",
        "P0113" to "Intake air temperature circuit high",
        "P0115" to "Engine coolant temperature circuit malfunction",
        "P0116" to "Engine coolant temperature range/performance",
        "P0117" to "Engine coolant temperature circuit low",
        "P0118" to "Engine coolant temperature circuit high",
        "P0120" to "Throttle position sensor A circuit malfunction",
        "P0121" to "Throttle position sensor A range/performance",
        "P0122" to "Throttle position sensor A circuit low",
        "P0123" to "Throttle position sensor A circuit high",
        "P0125" to "Insufficient coolant temperature for closed loop fuel control",
        "P0128" to "Coolant thermostat (coolant temp below regulating temperature)",
        "P0130" to "O2 sensor circuit malfunction (Bank 1 Sensor 1)",
        "P0131" to "O2 sensor circuit low voltage (Bank 1 Sensor 1)",
        "P0132" to "O2 sensor circuit high voltage (Bank 1 Sensor 1)",
        "P0133" to "O2 sensor slow response (Bank 1 Sensor 1)",
        "P0134" to "O2 sensor no activity detected (Bank 1 Sensor 1)",
        "P0135" to "O2 sensor heater circuit malfunction (Bank 1 Sensor 1)",
        "P0136" to "O2 sensor circuit malfunction (Bank 1 Sensor 2)",
        "P0137" to "O2 sensor circuit low voltage (Bank 1 Sensor 2)",
        "P0138" to "O2 sensor circuit high voltage (Bank 1 Sensor 2)",
        "P0139" to "O2 sensor slow response (Bank 1 Sensor 2)",
        "P0140" to "O2 sensor no activity detected (Bank 1 Sensor 2)",
        "P0141" to "O2 sensor heater circuit malfunction (Bank 1 Sensor 2)",
        "P0150" to "O2 sensor circuit malfunction (Bank 2 Sensor 1)",
        "P0151" to "O2 sensor circuit low voltage (Bank 2 Sensor 1)",
        "P0152" to "O2 sensor circuit high voltage (Bank 2 Sensor 1)",
        "P0153" to "O2 sensor slow response (Bank 2 Sensor 1)",
        "P0154" to "O2 sensor no activity detected (Bank 2 Sensor 1)",
        "P0155" to "O2 sensor heater circuit malfunction (Bank 2 Sensor 1)",
        "P0156" to "O2 sensor circuit malfunction (Bank 2 Sensor 2)",
        "P0157" to "O2 sensor circuit low voltage (Bank 2 Sensor 2)",
        "P0158" to "O2 sensor circuit high voltage (Bank 2 Sensor 2)",
        "P0161" to "O2 sensor heater circuit malfunction (Bank 2 Sensor 2)",
        "P0171" to "System too lean (Bank 1)",
        "P0172" to "System too rich (Bank 1)",
        "P0174" to "System too lean (Bank 2)",
        "P0175" to "System too rich (Bank 2)",
        "P0191" to "Fuel rail pressure sensor range/performance",
        "P0192" to "Fuel rail pressure sensor circuit low",
        "P0193" to "Fuel rail pressure sensor circuit high",
        "P0201" to "Injector circuit malfunction - cylinder 1",
        "P0202" to "Injector circuit malfunction - cylinder 2",
        "P0203" to "Injector circuit malfunction - cylinder 3",
        "P0204" to "Injector circuit malfunction - cylinder 4",
        "P0205" to "Injector circuit malfunction - cylinder 5",
        "P0206" to "Injector circuit malfunction - cylinder 6",
        "P0207" to "Injector circuit malfunction - cylinder 7",
        "P0208" to "Injector circuit malfunction - cylinder 8",
        "P0220" to "Throttle position sensor B circuit malfunction",
        "P0222" to "Throttle position sensor B circuit low",
        "P0223" to "Throttle position sensor B circuit high",
        "P0230" to "Fuel pump primary circuit malfunction",
        "P0234" to "Turbo/supercharger overboost condition",
        "P0299" to "Turbo/supercharger underboost condition",
        // Ignition / misfire
        "P0300" to "Random/multiple cylinder misfire detected",
        "P0301" to "Cylinder 1 misfire detected",
        "P0302" to "Cylinder 2 misfire detected",
        "P0303" to "Cylinder 3 misfire detected",
        "P0304" to "Cylinder 4 misfire detected",
        "P0305" to "Cylinder 5 misfire detected",
        "P0306" to "Cylinder 6 misfire detected",
        "P0307" to "Cylinder 7 misfire detected",
        "P0308" to "Cylinder 8 misfire detected",
        "P0316" to "Misfire detected on startup (first 1000 revolutions)",
        "P0320" to "Ignition/distributor engine speed input circuit",
        "P0325" to "Knock sensor 1 circuit malfunction (Bank 1)",
        "P0326" to "Knock sensor 1 circuit range/performance (Bank 1)",
        "P0327" to "Knock sensor 1 circuit low (Bank 1)",
        "P0328" to "Knock sensor 1 circuit high (Bank 1)",
        "P0332" to "Knock sensor 2 circuit low (Bank 2)",
        "P0335" to "Crankshaft position sensor A circuit malfunction",
        "P0336" to "Crankshaft position sensor A range/performance",
        "P0340" to "Camshaft position sensor A circuit malfunction (Bank 1)",
        "P0341" to "Camshaft position sensor A range/performance (Bank 1)",
        "P0345" to "Camshaft position sensor A circuit (Bank 2)",
        "P0351" to "Ignition coil A primary/secondary circuit",
        "P0352" to "Ignition coil B primary/secondary circuit",
        "P0353" to "Ignition coil C primary/secondary circuit",
        "P0354" to "Ignition coil D primary/secondary circuit",
        "P0355" to "Ignition coil E primary/secondary circuit",
        "P0356" to "Ignition coil F primary/secondary circuit",
        "P0357" to "Ignition coil G primary/secondary circuit",
        "P0358" to "Ignition coil H primary/secondary circuit",
        // Emission controls
        "P0400" to "Exhaust gas recirculation (EGR) flow malfunction",
        "P0401" to "EGR flow insufficient",
        "P0402" to "EGR flow excessive",
        "P0404" to "EGR circuit range/performance",
        "P0410" to "Secondary air injection system malfunction",
        "P0411" to "Secondary air injection incorrect flow",
        "P0420" to "Catalyst system efficiency below threshold (Bank 1)",
        "P0421" to "Warm-up catalyst efficiency below threshold (Bank 1)",
        "P0430" to "Catalyst system efficiency below threshold (Bank 2)",
        "P0440" to "Evaporative emission (EVAP) system malfunction",
        "P0441" to "EVAP system incorrect purge flow",
        "P0442" to "EVAP system small leak detected",
        "P0443" to "EVAP purge control valve circuit",
        "P0446" to "EVAP vent control circuit",
        "P0449" to "EVAP vent valve/solenoid circuit",
        "P0451" to "EVAP pressure sensor range/performance",
        "P0452" to "EVAP pressure sensor low input",
        "P0453" to "EVAP pressure sensor high input",
        "P0455" to "EVAP system large leak detected (often a loose gas cap)",
        "P0456" to "EVAP system very small leak detected",
        "P0457" to "EVAP system leak detected (fuel cap loose/off)",
        "P0460" to "Fuel level sensor circuit malfunction",
        "P0461" to "Fuel level sensor circuit range/performance",
        "P0462" to "Fuel level sensor circuit low",
        "P0463" to "Fuel level sensor circuit high",
        "P0480" to "Cooling fan 1 control circuit",
        "P0481" to "Cooling fan 2 control circuit",
        "P0496" to "EVAP high purge flow",
        "P0497" to "EVAP low purge flow",
        // Speed / idle
        "P0500" to "Vehicle speed sensor malfunction",
        "P0501" to "Vehicle speed sensor range/performance",
        "P0503" to "Vehicle speed sensor intermittent/erratic",
        "P0505" to "Idle air control system malfunction",
        "P0506" to "Idle speed lower than expected",
        "P0507" to "Idle speed higher than expected",
        "P0520" to "Engine oil pressure sensor/switch circuit",
        "P0521" to "Engine oil pressure sensor range/performance",
        "P0522" to "Engine oil pressure sensor low voltage",
        "P0523" to "Engine oil pressure sensor high voltage",
        "P0532" to "A/C refrigerant pressure sensor circuit low",
        "P0533" to "A/C refrigerant pressure sensor circuit high",
        "P0562" to "System voltage low",
        "P0563" to "System voltage high",
        "P0571" to "Brake switch A circuit",
        // Computer / output
        "P0600" to "Serial communication link malfunction",
        "P0601" to "Engine control module memory checksum error",
        "P0602" to "Control module programming error",
        "P0603" to "Control module keep-alive memory (KAM) error",
        "P0604" to "Control module RAM error",
        "P0606" to "Engine control module processor fault",
        "P0620" to "Generator control circuit",
        "P0621" to "Generator lamp control circuit",
        "P0622" to "Generator field control circuit",
        "P0641" to "Sensor reference voltage A circuit",
        "P0651" to "Sensor reference voltage B circuit",
        // Transmission
        "P0700" to "Transmission control system malfunction (check TCM codes)",
        "P0705" to "Transmission range sensor circuit (PRNDL)",
        "P0706" to "Transmission range sensor range/performance",
        "P0710" to "Transmission fluid temperature sensor circuit",
        "P0711" to "Transmission fluid temperature sensor range/performance",
        "P0715" to "Input/turbine speed sensor circuit",
        "P0716" to "Input/turbine speed sensor range/performance",
        "P0717" to "Input/turbine speed sensor no signal",
        "P0720" to "Output speed sensor circuit",
        "P0730" to "Incorrect gear ratio",
        "P0731" to "Gear 1 incorrect ratio",
        "P0732" to "Gear 2 incorrect ratio",
        "P0733" to "Gear 3 incorrect ratio",
        "P0734" to "Gear 4 incorrect ratio",
        "P0735" to "Gear 5 incorrect ratio",
        "P0740" to "Torque converter clutch circuit malfunction",
        "P0741" to "Torque converter clutch stuck off / performance",
        "P0742" to "Torque converter clutch stuck on",
        "P0750" to "Shift solenoid A malfunction",
        "P0755" to "Shift solenoid B malfunction",
        "P0760" to "Shift solenoid C malfunction",
        "P0765" to "Shift solenoid D malfunction",
        "P0841" to "Transmission fluid pressure sensor/switch A range/performance",
        "P0868" to "Transmission fluid pressure low",
        // Hybrid / misc
        "P0A80" to "Replace hybrid battery pack",
        "P1000" to "OBD systems readiness test not complete (Ford - normal after clearing codes)",
        "P1101" to "MAF sensor out of self-test range (Ford)",
        "P1131" to "Lack of upstream O2 sensor switch - lean (Ford)",
        "P1133" to "HO2S insufficient switching (Bank 1 Sensor 1)",
        "P1151" to "Lack of upstream O2 sensor switch - lean (Bank 2, Ford)",
        "P1450" to "Unable to bleed up fuel tank vacuum (Ford EVAP)",
        "P1516" to "Idle air control/throttle actuator - check throttle body",
        "P2096" to "Post catalyst fuel trim system too lean (Bank 1)",
        "P2097" to "Post catalyst fuel trim system too rich (Bank 1)",
        "P2098" to "Post catalyst fuel trim system too lean (Bank 2)",
        "P2099" to "Post catalyst fuel trim system too rich (Bank 2)",
        "P2101" to "Throttle actuator control motor circuit range/performance",
        "P2104" to "Throttle actuator control system - forced idle",
        "P2105" to "Throttle actuator control system - forced engine shutdown",
        "P2106" to "Throttle actuator control system - forced limited power",
        "P2110" to "Throttle actuator control system - forced limited RPM",
        "P2111" to "Throttle actuator control system - stuck open",
        "P2112" to "Throttle actuator control system - stuck closed",
        "P2119" to "Throttle actuator control throttle body range/performance",
        "P2122" to "Accelerator pedal position sensor D circuit low",
        "P2127" to "Accelerator pedal position sensor E circuit low",
        "P2135" to "Throttle/pedal position sensor A/B voltage correlation",
        "P2138" to "Accelerator pedal position sensor D/E voltage correlation",
        "P2187" to "System too lean at idle (Bank 1)",
        "P2188" to "System too rich at idle (Bank 1)",
        "P2189" to "System too lean at idle (Bank 2)",
        "P2195" to "O2 sensor signal stuck lean (Bank 1 Sensor 1)",
        "P2196" to "O2 sensor signal stuck rich (Bank 1 Sensor 1)",
        "P2197" to "O2 sensor signal stuck lean (Bank 2 Sensor 1)",
        "P2270" to "O2 sensor signal stuck lean (Bank 1 Sensor 2)",
        "P2271" to "O2 sensor signal stuck rich (Bank 1 Sensor 2)",
        "P2272" to "O2 sensor signal stuck lean (Bank 2 Sensor 2)",
        "P2279" to "Intake air system leak",
        "P2440" to "Secondary air injection switching valve stuck open",
        "P2A00" to "O2 sensor circuit range/performance (Bank 1 Sensor 1)",
        "P2A03" to "O2 sensor circuit range/performance (Bank 2 Sensor 1)",
        // Network
        "U0001" to "High speed CAN communication bus",
        "U0073" to "Control module communication bus A off",
        "U0100" to "Lost communication with engine control module (ECM/PCM)",
        "U0101" to "Lost communication with transmission control module (TCM)",
        "U0121" to "Lost communication with anti-lock brake system (ABS) module",
        "U0140" to "Lost communication with body control module (BCM)",
        "U0155" to "Lost communication with instrument panel cluster",
        "U0401" to "Invalid data received from ECM/PCM"
    )

    fun describe(code: String): String {
        codes[code]?.let { return it }
        if (code.length < 5) return "Unknown code"
        val manufacturer = when (code[0]) {
            'P' -> code[1] == '1' || code[1] == '3'
            else -> code[1] == '1' || code[1] == '2'
        }
        val system = when (code[0]) {
            'P' -> when (code[2]) {
                '0', '1', '2' -> "Fuel and air metering"
                '3' -> "Ignition system or misfire"
                '4' -> "Auxiliary emission controls"
                '5' -> "Vehicle speed, idle control or auxiliary inputs"
                '6' -> "Computer or output circuits"
                '7', '8', '9' -> "Transmission"
                'A', 'B', 'C' -> "Hybrid propulsion"
                else -> "Powertrain"
            }
            'B' -> "Body (airbags, lighting, comfort)"
            'C' -> "Chassis (ABS, steering, suspension)"
            'U' -> "Network communication"
            else -> "Unknown"
        }
        return if (manufacturer) "$system - manufacturer-specific code" else "$system - generic code"
    }
}
